---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        Optimized for Kindle and iPad
        Almost 9000 pages of content
        Includes a free copy of 1st Edition PDF
    media:
      - ebook
    price: 3500

  -
    code: all
    name: "HTML, Ebook, and Screencasts"
    description:
      |
        Includes all 50 screencasts
        eBook formats for Kindle, Nook, and PDF
        Read online.
    media:
      - ebook
    price: 12500
    regular_price: 19900

authors:
  -
    name: "Matt Aimonetti"
    image: /images/matt_aimonetti_sq_2013_small.jpg
    contact_email: "mattaimonetti@gmail.com"
    bio:
      |
        Matt is [Splice](https://splice.com) cofounder.
        He's an active community member who contributed to many projects including the Go language. Matt is also a published author and who maintains his 
         [personal blog](http://matt.aimonetti.net) about tech and programming in general.

faq:
  -
    question: "Is this book done?"
    answer: "Not yet, I'm still working on it."
  -
    question: "Is this book free?"
    answer: "Yes and will stay free even when done."
  -
    question: "I found a typo or have suggestion, can I contribute?"
    answer: "Absolutely, send a pull request to [the book repository](https://github.com/GoBootcamp/book)."
  -
    question: "Do I need to have Go installed?"
    answer: "No, all code examples can be executed and modified from your browser as long as have you internet."
  -
    question: "Some of the material seems familiar"
    answer: "The book is largely based on the [Go tour](https://tour.golang.org/)"

testimonials:
  -
    name: "Evan Phoenix"
    title: "Code Chef / Mad Scientist"
    image: /images/evan.jpeg
    text: "I'm sure this book is great, but I didn't read it."
  -
    name: "Chad Fowler"
    title: "Author, technologist, consultant, speaker, teacher, musician, organizer"
    image: /images/chad.jpg
    text: "I like Haskell better, but if you want to write Go, you probably should read this awesome (free) book."

marketing_content: ''

contact_email: ''
hide_custom_domain_footer: false
